---
settings:
  name: NetApp NFS Plug-in for VMware VAAI
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: it-it,us-en,de-de,es-es,fr-fr,pt-br,ja-jp,ko-kr,zh-cn,zh-tw
sidebar:
  entries:
  - title: Documenti NetApp NFS Plug-in per VMware VAAI
    url: "/index.html"
  - title: Note di rilascio
    url: "/releasenotes.html"
  - title: Installare e configurare
    entries:
    - title: Installare il plug-in NetApp NFS per VMware VAAI
      url: "/task-install-netapp-nfs-plugin-for-vmware-vaai.html"
    - title: Configurare le policy di esportazione per ONTAP per consentire VAAI su
        NFS
      url: "/task-configure-export-policies-for-clustered-data-ontap-to-allow-vaai-over-nfs.html"
  - title: Note legali
    url: "/legal-notices.html"
